---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.prometheus-blackbox-exporter/summary: "[Prometheus Blackbox Exporter](https://github.com/prometheus/blackbox_exporter)\
      \ - blackbox probing of endpoints over HTTP, HTTPS and TCP."
    fabric8.prometheus-blackbox-exporter/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png"
    description: "Prometheus Blackbox Exporter - blackbox probing of endpoints over\
      \ HTTP, HTTPS and TCP.\n\n[https://github.com/prometheus/blackbox_exporter](https://github.com/prometheus/blackbox_exporter)\n"
  labels: {}
  name: "prometheus-blackbox-exporter"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/port: "9115"
      prometheus.io/scrape: "true"
    labels:
      project: "prometheus-blackbox-exporter"
      component: "prometheus"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "blackbox"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 9115
    selector:
      project: "prometheus-blackbox-exporter"
      component: "prometheus"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "stuff"
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "prometheus-blackbox-exporter"
      component: "prometheus"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "prometheus-blackbox-exporter"
  spec:
    replicas: 1
    selector:
      project: "prometheus-blackbox-exporter"
      component: "prometheus"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "prometheus-blackbox-exporter"
          component: "prometheus"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/prometheus-blackbox:2.2.75-SNAPSHOT"
          livenessProbe:
            tcpSocket:
              port: 9115
          name: "prometheus-blackbox-exporter"
          ports:
          - containerPort: 9115
            name: "http"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
