---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.hubot-notifier/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
    description: "Provides [Chat](http://fabric8.io/guide/chat.html) using [Hubot](https://hubot.github.com/)\
      \ as the bot framework and [Slack](https://slack.com/) as the chat service"
    fabric8.hubot-notifier/summary: "Watches the OpenShift environment and notifies\
      \ Hubot of events such as builds completing or failing"
    fabric8.chat-slack/summary: "Sonatype helps open source projects to set up Maven\
      \ repositories on https://oss.sonatype.org/"
    fabric8.chat-slack/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/packages/chat-slack/src/main/fabric8/icon.png"
  labels: {}
  name: "chat-slack"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      package: "chat-slack"
    name: "hubot"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      targetPort: 8080
    selector:
      name: "hubot-slack"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "stuff"
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "hubotNotifier"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "chat-slack"
    name: "hubot-notifier"
  spec:
    replicas: 1
    selector:
      project: "hubotNotifier"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "hubotNotifier"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
          package: "chat-slack"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "HUBOT_KUBERNETES_ROOM"
            value: "#fabric8_${namespace}"
          - name: "HUBOT_USERNAME"
            value: "${HUBOT_USERNAME}"
          - name: "HUBOT_PASSWORD"
            value: "${HUBOT_PASSWORD}"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/hubot-notifier:2.2.75-SNAPSHOT"
          name: "hubot-notifier"
          ports:
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        serviceAccountName: "fabric8"
        volumes: []
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "stuff"
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      name: "hubot-slack"
      package: "chat-slack"
    name: "hubot-slack"
  spec:
    replicas: 1
    selector:
      name: "hubot-slack"
    template:
      metadata:
        annotations: {}
        labels:
          name: "hubot-slack"
          package: "chat-slack"
        name: "hubot-slack"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "HUBOT_SLACK_TOKEN"
            value: "${HUBOT_SLACK_TOKEN}"
          - name: "HUBOT_GRAFANA_HOST"
            value: "${HUBOT_SLACK_GRAFANA_HOST}"
          - name: "HUBOT_GRAFANA_API_KEY"
            value: "${HUBOT_SLACK_GRAFANA_API_KEY}"
          - name: "HUBOT_JENKINS_URL"
            value: "${HUBOT_JENKINS_URL}"
          image: "fabric8/hubot-slack:2.2.75-SNAPSHOT"
          name: "hubot-slack"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters:
- description: "The DNS domain added to the serviceName.namespace.svc. to make the\
    \ DNS name"
  name: "KUBERNETES_DNS_DOMAIN"
  value: "cluster.local"
- description: "The password for Hubot to login to the chat service"
  name: "HUBOT_PASSWORD"
  value: "RedHat$1"
- description: "The username for Hubot to login to the chat service"
  name: "HUBOT_USERNAME"
  value: "fabric8"
- description: "The token for Hubot to login to Slack"
  name: "HUBOT_SLACK_TOKEN"
- description: "Host for your Grafana 2.0 install, e.g. 'http://play.grafana.org'"
  name: "HUBOT_SLACK_GRAFANA_HOST"
  value: "http://grafana2.default.svc.cluster.local"
- description: "API key for a particular user"
  name: "HUBOT_SLACK_GRAFANA_API_KEY"
- description: "The URL for the Jenkins CI server"
  name: "HUBOT_JENKINS_URL"
  value: "http://jenkins.default.svc.cluster.local"
