---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.templates/summary: "Implements the OpenShift Templates REST API so templates\
      \ can be used on vanilla Kubernetes environments"
    description: "Implements the OpenShift Templates REST API so templates can be\
      \ used on vanilla Kubernetes environments "
    fabric8.templates/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/templates/src/main/fabric8/icon.svg"
  labels: {}
  name: "templates"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "templates"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "templates"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "templates"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "stuff"
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "templates"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "templates"
  spec:
    replicas: 1
    selector:
      project: "templates"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "templates"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "DATA_DIR"
            value: "/data/templates"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/templates:2.2.75-SNAPSHOT"
          name: "templates"
          ports:
          - containerPort: 8080
            name: "http"
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts:
          - mountPath: "/data"
            name: "template-data"
            readOnly: false
        imagePullSecrets: []
        nodeSelector: {}
        volumes:
        - gitRepo:
            repository: "https://github.com/fabric8io/templates.git"
            revision: "master"
          name: "template-data"
parameters: []
