---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "Elasticsearch is a search server based on Lucene. It provides a\
      \ distributed, multitenant-capable full-text search engine with a RESTful web\
      \ interface and schema-free JSON documents. Elasticsearch is developed in Java\
      \ and is released as open source under the terms of the Apache License.\n\n\
      More details on the <a href=\"http://wikipedia.org/wiki/Elasticsearch\" target=\"\
      wikipedia\">Elasticsearch wikipedia page</a> or the <a href=\"http://elasticsearch.com/\"\
      \ target=\"elasticsearch\">Elasticsearch home page</a>.\n.\n"
    fabric8.elasticsearch/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
    fabric8.elasticsearch/summary: "[elasticsearch](http://elasticsearch.com/) provides\
      \ distributed RESTful search and analytics"
  labels: {}
  name: "elasticsearch"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "elasticsearch"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "elasticsearch"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 9200
      protocol: "TCP"
      targetPort: 9200
    selector:
      project: "elasticsearch"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels: {}
    name: "elasticsearch-cluster"
  spec:
    clusterIP: "None"
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - name: ""
      port: 9300
      protocol: "TCP"
      targetPort: 9300
    selector:
      provider: "fabric8"
      project: "elasticsearch"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/git-branch: "stuff"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "elasticsearch"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "elasticsearch"
  spec:
    replicas: 1
    selector:
      project: "elasticsearch"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "elasticsearch"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "SERVICE_DNS"
            value: "elasticsearch-cluster"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/elasticsearch-k8s:1.5.2"
          livenessProbe:
            initialDelaySeconds: 60
            tcpSocket:
              port: 9300
          name: "elasticsearch"
          ports:
          - containerPort: 9200
            name: "http"
          - containerPort: 9300
            name: "transport"
          readinessProbe:
            httpGet:
              path: "/_template/logstash"
              port: 9200
            initialDelaySeconds: 60
          securityContext: {}
          volumeMounts:
          - mountPath: "/usr/share/elasticsearch/data"
            name: "elasticsearch-data"
            readOnly: false
        - args: []
          command: []
          env: []
          image: "fabric8/elasticsearch-logstash-template:2.2.75-SNAPSHOT"
          name: "logstash-template"
          ports: []
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes:
        - emptyDir:
            medium: ""
          name: "elasticsearch-data"
parameters: []
