---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "The <a href=\"http://brackets.io/\" target=\"brackets\">Brackets</a>\
      \ editor for working with files in a git repository"
    fabric8.brackets/summary: "[Brackets](http://brackets.io/) editor for working\
      \ with files in git"
    fabric8.brackets/iconUrl: "data:image/svg+xml;charset=UTF-8;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHdpZHRoPSIxMjBweCIgaGVpZ2h0PSIxMjBweCI+Cgk8ZGVmcz4KCQk8bGluZWFyR3JhZGllbnQgaWQ9ImZyYW1lIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjQzMy41IiB5MT0iLTE4NSIgeDI9IjQzMy41IiB5Mj0iLTI3NyIgZ3JhZGllbnRUcmFuc2Zvcm09Im1hdHJpeCgxIDAgMCAtMSAtMzczLjUgLTE3NykiPgoJCQk8c3RvcCBvZmZzZXQ9IjAiIHN0b3AtY29sb3I9IiMyOUFCRTIiLz4KCQkJPHN0b3Agb2Zmc2V0PSIwLjQ3NTciIHN0b3AtY29sb3I9IiMyOEE5RTEiLz4KCQkJPHN0b3Agb2Zmc2V0PSIwLjY2MzkiIHN0b3AtY29sb3I9IiMyM0EyREMiLz4KCQkJPHN0b3Agb2Zmc2V0PSIwLjgwMTIiIHN0b3AtY29sb3I9IiMxQTk2RDQiLz4KCQkJPHN0b3Agb2Zmc2V0PSIwLjkxMyIgc3RvcC1jb2xvcj0iIzBFODVDOSIvPgoJCQk8c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiMwMDcxQkMiLz4KCQk8L2xpbmVhckdyYWRpZW50PgoJCTxmaWx0ZXIgaWQ9ImJsdXIiIHg9Ii0xMCIgeT0iLTEwIiB3aWR0aD0iMTIiIGhlaWdodD0iMTIiPgoJCQk8ZmVHYXVzc2lhbkJsdXIgaW49IlNvdXJjZUdyYXBoaWMiIHN0ZERldmlhdGlvbj0iMSIvPgoJCTwvZmlsdGVyPgoJPC9kZWZzPgoJPHJlY3QgaWQ9InNoYWRvdyIgeD0iMTAiIHk9IjkiIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiByeD0iMjAiIHJ5PSIyMCIgb3BhY2l0eT0iLjUiIGZpbHRlcj0idXJsKCNibHVyKSIvPgoJPHJlY3QgeD0iMTAiIHk9IjU4IiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjUwIiByeD0iMjAiIHJ5PSIyMCIgZmlsbD0iIzExNUE5MSIvPgoJPHJlY3QgeD0iMTAiIHk9IjgiIHdpZHRoPSIxMDAiIGhlaWdodD0iOTIiIHJ4PSIyMCIgcnk9IjIwIiBmaWxsPSJ1cmwoI2ZyYW1lKSIvPgoJPHJlY3QgeD0iMjIiIHk9IjIwIiB3aWR0aD0iNzYiIGhlaWdodD0iNjgiIHJ4PSIxMCIgcnk9IjEwIiBmaWxsPSIjZmZmIi8+Cgk8cGF0aCBpZD0ic2hhZG93MiIgb3BhY2l0eT0iLjUiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAsIDEpIiBmaWx0ZXI9InVybCgjYmx1cikiIGQ9Ik01NywyOHYxMkg0M3YyNmgxNHYxM0gzMFYyOEg1N3pNOTAsMjh2NTFINjNWNjZoMTVWNDBINjNWMjhIOTB6Ii8+Cgk8cGF0aCBpZD0iYnJhY2tldHMiIGZpbGw9IiM0RDRENEQiIGQ9Ik01NywyOHYxMkg0M3YyNmgxNHYxM0gzMFYyOEg1N3pNOTAsMjh2NTFINjNWNjZoMTVWNDBINjNWMjhIOTB6Ii8+Cjwvc3ZnPgo="
  labels: {}
  name: "brackets"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "brackets"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "brackets"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 80
    selector:
      project: "brackets"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "stuff"
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "brackets"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "brackets"
  spec:
    replicas: 1
    selector:
      project: "brackets"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "brackets"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/brackets:2.2.75-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "brackets"
          ports:
          - containerPort: 80
            name: "http"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
