---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "Fabric8 Forge"
    fabric8.fabric8-forge/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/fabric8-forge/src/main/fabric8/icon.svg"
    fabric8.fabric8-forge/summary: "Fabric8 Forge"
  labels: {}
  name: "fabric8-forge"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "fabric8Forge"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "fabric8-forge"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "fabric8Forge"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "stuff"
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "fabric8Forge"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "fabric8-forge"
  spec:
    replicas: 1
    selector:
      project: "fabric8Forge"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "fabric8Forge"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "JENKINS_SEED_JOB"
            value: "seed"
          - name: "FABRIC8_DEFAULT_ENVIRONMENTS"
            value: "${FABRIC8_DEFAULT_ENVIRONMENTS}"
          - name: "JENKINS_WORKFLOW_GIT_REPOSITORY"
            value: "${JENKINS_WORKFLOW_GIT_REPOSITORY}"
          - name: "KUBERNETES_TRUST_CERTIFICATES"
            value: "true"
          - name: "SKIP_TLS_VERIFY"
            value: "true"
          - name: "JENKINS_GOGS_PASSWORD"
            value: "${JENKINS_GOGS_PASSWORD}"
          - name: "JENKINS_GOGS_USER"
            value: "${JENKINS_GOGS_USER}"
          - name: "FABRIC8_ARCHETYPES_VERSION"
            value: "2.2.65"
          - name: "JENKINS_GOGS_EMAIL"
            value: "${JENKINS_GOGS_EMAIL}"
          - name: "KUBERNETES_MASTER"
            value: "https://kubernetes.default.svc"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/fabric8-forge:2.2.75-SNAPSHOT"
          name: "fabric8-forge"
          ports:
          - containerPort: 8778
            name: "jolokia"
          readinessProbe:
            httpGet:
              path: "/_ping"
              port: 8080
            initialDelaySeconds: 30
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        serviceAccountName: "fabric8"
        volumes: []
parameters:
- description: "The email address of the Jenkins user on Gogs"
  name: "JENKINS_GOGS_EMAIL"
  value: "gogsadmin@fabric8.local"
- description: "The user name for Jenkins to login to Gogs"
  name: "JENKINS_GOGS_USER"
  value: "gogsadmin"
- description: "The list of default environment names to actual kubernetes namespaces"
  name: "FABRIC8_DEFAULT_ENVIRONMENTS"
  value: "Testing=${buildName}-testing,Staging=${buildName}-staging,Production=${buildName}-prod"
- description: "The password for Jenkins to login to Gogs"
  name: "JENKINS_GOGS_PASSWORD"
  value: "RedHat$1"
- description: "The git clone URL for the jenkins workflow repository which can be\
    \ reused across projects"
  name: "JENKINS_WORKFLOW_GIT_REPOSITORY"
  value: "https://github.com/fabric8io/jenkins-workflow-library.git"
