---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "sonarqube"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 8080
      targetPort: 9000
    selector:
      name: "sonarqube"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    labels:
      name: "sonarqube"
    name: "sonarqube"
  spec:
    replicas: 1
    selector:
      name: "sonarqube"
    template:
      metadata:
        labels:
          name: "sonarqube"
        name: "sonarqube"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "DB_PORT_3306_TCP_ADDR"
            value: "localhost"
          image: "tpires/sonar-server"
          name: "sonarqube-server-container"
          ports:
          - containerPort: 9000
            protocol: "TCP"
          volumeMounts: []
        - args: []
          command: []
          env: []
          image: "tpires/sonar-mysql"
          name: "sonarqube-database-container"
          ports:
          - containerPort: 3306
            protocol: "TCP"
          volumeMounts: []
        imagePullSecrets: []
        volumes: []
kind: "List"
description: "Creates a sonarqube Server"
