---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "Provides centralised historical [Metrics](http://fabric8.io/guide/metrics.html)\
      \ and alerting using [Prometheus](prometheus) as the back end and [Grafana2](http://grafana.org/)\
      \ as the front end"
    fabric8.grafana2/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/grafana2/src/main/fabric8/icon.png"
    fabric8.grafana2/summary: "[Grafana](http://grafana.org/) 2 console for viewing\
      \ metrics stored in various storage backends"
    fabric8.prometheus/summary: "[Prometheus](http://prometheus.io/) - an open-source\
      \ service monitoring system and time series database"
    fabric8.prometheus/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus/src/main/fabric8/icon.png"
    fabric8.metrics/summary: "Sonatype helps open source projects to set up Maven\
      \ repositories on https://oss.sonatype.org/"
    fabric8.metrics/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/packages/metrics/src/main/fabric8/icon.png"
  labels: {}
  name: "metrics"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "grafana2"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "metrics"
    name: "grafana2"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 3000
    selector:
      project: "grafana2"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/port: "9090"
      prometheus.io/scrape: "true"
    labels:
      project: "prometheus"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "metrics"
    name: "prometheus"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 9090
    selector:
      project: "prometheus"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "stuff"
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "grafana2"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "metrics"
    name: "grafana2"
  spec:
    replicas: 1
    selector:
      project: "grafana2"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "grafana2"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
          package: "metrics"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/grafana:2.5.0"
          name: "grafana2"
          ports:
          - containerPort: 3000
            name: "http"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "stuff"
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "prometheus"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "metrics"
    name: "prometheus"
  spec:
    replicas: 1
    selector:
      project: "prometheus"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "prometheus"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
          package: "metrics"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/prometheus-kubernetes:2.2.75-SNAPSHOT"
          livenessProbe:
            tcpSocket:
              port: 9090
          name: "prometheus"
          ports:
          - containerPort: 9090
            name: "http"
          securityContext: {}
          volumeMounts:
          - mountPath: "/prometheus"
            name: "prometheus-data"
            readOnly: false
        imagePullSecrets: []
        nodeSelector: {}
        serviceAccountName: "metrics"
        volumes:
        - emptyDir:
            medium: ""
          name: "prometheus-data"
parameters: []
