---
name: "hubot-notifier"
home: "http://fabric8.io/hubot-notifier/"
version: "2.2.75-SNAPSHOT"
description: "Watches the OpenShift environment and notifies Hubot of events such\
  \ as builds completing or failing"
maintainers:
- "Fabric8 Development Team <fabric8@googlegroups.com>"
