---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "Provides centralised [Logging](http://fabric8.io/guide/logging.html)\
      \ using [Elasticsearch](http://wikipedia.org/wiki/Elasticsearch) as the back\
      \ end and [Kibana](http://www.elasticsearch.org/overview/kibana/) as the front\
      \ end\n"
    fabric8.elasticsearch/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
    fabric8.elasticsearch/summary: "[elasticsearch](http://elasticsearch.com/) provides\
      \ distributed RESTful search and analytics"
    fabric8.kibana/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg"
    fabric8.kibana/summary: "Awesome front-end for Elasticsearch"
    fabric8.logging/summary: "Sonatype helps open source projects to set up Maven\
      \ repositories on https://oss.sonatype.org/"
    fabric8.logging/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/packages/logging/src/main/fabric8/icon.svg"
  labels: {}
  name: "logging"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "elasticsearch"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "logging"
    name: "elasticsearch"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 9200
      protocol: "TCP"
      targetPort: 9200
    selector:
      project: "elasticsearch"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      package: "logging"
    name: "elasticsearch-cluster"
  spec:
    clusterIP: "None"
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - name: ""
      port: 9300
      protocol: "TCP"
      targetPort: 9300
    selector:
      provider: "fabric8"
      project: "elasticsearch"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "kibana"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "logging"
    name: "kibana"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 5601
    selector:
      project: "kibana"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/git-branch: "stuff"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "elasticsearch"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "logging"
    name: "elasticsearch"
  spec:
    replicas: 1
    selector:
      project: "elasticsearch"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "elasticsearch"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
          package: "logging"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "SERVICE_DNS"
            value: "elasticsearch-cluster"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/elasticsearch-k8s:1.5.2"
          livenessProbe:
            initialDelaySeconds: 60
            tcpSocket:
              port: 9300
          name: "elasticsearch"
          ports:
          - containerPort: 9200
            name: "http"
          - containerPort: 9300
            name: "transport"
          readinessProbe:
            httpGet:
              path: "/_template/logstash"
              port: 9200
            initialDelaySeconds: 60
          securityContext: {}
          volumeMounts:
          - mountPath: "/usr/share/elasticsearch/data"
            name: "elasticsearch-data"
            readOnly: false
        - args: []
          command: []
          env: []
          image: "fabric8/elasticsearch-logstash-template:2.2.75-SNAPSHOT"
          name: "logstash-template"
          ports: []
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes:
        - emptyDir:
            medium: ""
          name: "elasticsearch-data"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/git-branch: "stuff"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "kibana"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "logging"
    name: "kibana"
  spec:
    replicas: 1
    selector:
      project: "kibana"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "kibana"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
          package: "logging"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "ELASTICSEARCH_SERVICE_NAME"
            value: "ELASTICSEARCH"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/kibana4:4.1.2"
          livenessProbe:
            tcpSocket:
              port: 5601
          name: "kibana"
          ports:
          - containerPort: 5601
            name: "http"
          securityContext: {}
          volumeMounts: []
        - args: []
          command: []
          env:
          - name: "ELASTICSEARCH_SERVICE_NAME"
            value: "ELASTICSEARCH"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/kibana-config:2.2.75-SNAPSHOT"
          name: "kibana-config"
          ports: []
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
