---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.hubot-letschat/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-letschat/src/main/fabric8/icon.png"
    description: "Provides [Chat](http://fabric8.io/guide/chat.html) using [Hubot](https://hubot.github.com/)\
      \ as the bot framework and [Let's Chat](https://github.com/sdelements/lets-chat)\
      \ as the chat server"
    fabric8.hubot-letschat/summary: "[Hubot](http://hubot.github.com) chat bot for\
      \ Lets Chat"
    fabric8.hubot-notifier/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
    fabric8.hubot-notifier/summary: "Watches the OpenShift environment and notifies\
      \ Hubot of events such as builds completing or failing"
    fabric8.chat-letschat/summary: "Sonatype helps open source projects to set up\
      \ Maven repositories on https://oss.sonatype.org/"
    fabric8.chat-letschat/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/packages/chat-letschat/src/main/fabric8/icon.png"
  labels: {}
  name: "chat-letschat"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "hubot-letschat"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "chat-letschat"
    name: "hubot"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "hubot-letschat"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      provider: "fabric8"
      project: "hubot-letschat"
      package: "chat-letschat"
    name: "hubot-jenkins-notifier"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 5555
      protocol: "TCP"
      targetPort: 5555
    selector:
      provider: "fabric8"
      project: "hubot-letschat"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      package: "chat-letschat"
    name: "letschat"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      targetPort: 5000
    selector:
      name: "letschat"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/git-branch: "stuff"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "hubot-letschat"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "chat-letschat"
    name: "hubot-letschat"
  spec:
    replicas: 1
    selector:
      project: "hubot-letschat"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "hubot-letschat"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
          package: "chat-letschat"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "HUBOT_LCB_ROOMS"
            value: "${LETSCHAT_DEFAULT_ROOMS}"
          - name: "HUBOT_GRAFANA_API_KEY"
            value: "${HUBOT_GRAFANA_API_KEY}"
          - name: "HUBOT_LOG_LEVEL"
            value: "true"
          - name: "LETSCHAT_HUBOT_PASSWORD"
            value: "${LETSCHAT_HUBOT_PASSWORD}"
          - name: "HUBOT_GRAFANA_HOST"
            value: "${HUBOT_GRAFANA_HOST}"
          - name: "HUBOT_JENKINS_URL"
            value: "${HUBOT_JENKINS_URL}"
          - name: "HUBOT_LCB_TOKEN"
            value: "${LETSCHAT_HUBOT_TOKEN}"
          - name: "LETSCHAT_HUBOT_SCRIPTS"
            value: "${LETSCHAT_HUBOT_SCRIPTS}"
          - name: "LETSCHAT_HUBOT_USERNAME"
            value: "${LETSCHAT_HUBOT_USERNAME}"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/hubot-letschat:v1.0.0"
          name: "hubot-letschat"
          ports:
          - containerPort: 8080
            name: "http"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "stuff"
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      project: "hubotNotifier"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
      package: "chat-letschat"
    name: "hubot-notifier"
  spec:
    replicas: 1
    selector:
      project: "hubotNotifier"
      provider: "fabric8"
      version: "2.2.75-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "hubotNotifier"
          provider: "fabric8"
          version: "2.2.75-SNAPSHOT"
          group: "io.fabric8.devops.apps"
          package: "chat-letschat"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "HUBOT_KUBERNETES_ROOM"
            value: "#fabric8_${namespace}"
          - name: "HUBOT_USERNAME"
            value: "${HUBOT_USERNAME}"
          - name: "HUBOT_PASSWORD"
            value: "${HUBOT_PASSWORD}"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/hubot-notifier:2.2.75-SNAPSHOT"
          name: "hubot-notifier"
          ports:
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        serviceAccountName: "fabric8"
        volumes: []
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "stuff"
      fabric8.io/git-commit: "b37fca11f6cd7a789d0f1d54825f0557b39112d4"
      fabric8.io/build-url: "http://jenkins.vagrant.f8/job/oss-parent"
    labels:
      name: "letschat"
      provider: "fabric8"
      package: "chat-letschat"
    name: "letschat"
  spec:
    replicas: 1
    selector:
      name: "letschat"
    template:
      metadata:
        annotations: {}
        labels:
          name: "letschat"
          provider: "fabric8"
          package: "chat-letschat"
        name: "letschat"
      spec:
        containers:
        - args: []
          command: []
          env: []
          image: "mongo"
          name: "letschat-mongodb"
          ports:
          - containerPort: 27017
            protocol: "TCP"
          volumeMounts: []
        - args: []
          command: []
          env:
          - name: "LETSCHAT_CREATE_HUBOT_USER"
            value: "true"
          - name: "LETSCHAT_HUBOT_TOKEN"
            value: "${LETSCHAT_HUBOT_TOKEN}"
          - name: "LETSCHAT_HUBOT_PASSWORD"
            value: "${HUBOT_PASSWORD}"
          - name: "LETSCHAT_HUBOT_USERNAME"
            value: "${HUBOT_USERNAME}"
          - name: "LETSCHAT_HUBOT_EMAIL"
            value: "fabric8-admin@googlegroups.com"
          - name: "LETSCHAT_HUBOT_FIRST_NAME"
            value: "fabric8"
          - name: "LETSCHAT_HUBOT_LAST_NAME"
            value: "rocks"
          - name: "LETSCHAT_HUBOT_DISPLAY_NAME"
            value: "fabric8"
          - name: "LETSCHAT_DEFAULT_ROOMS"
            value: "${LETSCHAT_DEFAULT_ROOMS}"
          - name: "LCB_NOROBOTS"
            value: "false"
          - name: "LCB_FILES_ENABLE"
            value: "true"
          - name: "LCB_DATABASE_URI"
            value: "mongodb://127.0.0.1:27017/letschat"
          image: "fabric8/lets-chat:2.2.75-SNAPSHOT"
          name: "letschat"
          ports:
          - containerPort: 5000
            protocol: "TCP"
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters:
- description: "API key for a particular user"
  name: "HUBOT_GRAFANA_API_KEY"
- description: "The password for the Fabric8 Hubot bot"
  name: "LETSCHAT_HUBOT_PASSWORD"
  value: "RedHat$1"
- description: "Comma delimited list of rooms for hubot to join on startup"
  name: "LETSCHAT_DEFAULT_ROOMS"
  value: "fabric8_default"
- description: "The username for the Fabric8 Hubot bot"
  name: "LETSCHAT_HUBOT_USERNAME"
  value: "fabric8"
- description: "Coffeescripts for hubot"
  name: "LETSCHAT_HUBOT_SCRIPTS"
  value: "https://github.com/fabric8io/fabric8-hubot-scripts.git"
- description: "The URL for the Jenkins CI server"
  name: "HUBOT_JENKINS_URL"
  value: "http://jenkins.default.svc.cluster.local"
- description: "Host for your Grafana 2.0 install, e.g. 'http://play.grafana.org'"
  name: "HUBOT_GRAFANA_HOST"
- description: "The DNS domain added to the serviceName.namespace.svc. to make the\
    \ DNS name"
  name: "KUBERNETES_DNS_DOMAIN"
  value: "cluster.local"
- description: "The password for Hubot to login to the chat service"
  name: "HUBOT_PASSWORD"
  value: "RedHat$1"
- description: "The username for Hubot to login to the chat service"
  name: "HUBOT_USERNAME"
  value: "fabric8"
